### ISSUE TITLE
Update some problematic dependencies

### ISSUE THREAD

**Issue by tripu** [w3c/echidna-manifester#4]
```
$ npm install
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
⋮
```

Also, move from `phantomjs` to `phantomjs-prebuilt`?

**Comment by tripu** [comment]
Note to self: @marcoscaceres [has &ldquo;been using latest Phantomjs-prebuilt here and it works great&rdquo;](https://github.com/w3c/respec/issues/604#issuecomment-195129887); bug him if I'm stuck with the change.

**Comment by tripu** [comment]
&hellip;or [`nightmare`](https://github.com/w3c/respec/pull/678).

**Comment by marcoscaceres** [comment]
Nightmare is pretty good. If you want to go bare metal, Electron is also pretty awesome.
